### ISSUE TITLE
show_model が参照するプロパティ

### ISSUE THREAD

**Issue by bromne** [ahahsak/VB_HMM#5]
show_model で参照するプロパティ `model.mu` や `model.cv` は、 `VB_HMM` を実際に外部から利用するとき、どのように定義するのでしょうか？
 `show_model` のテストで書かれているように、（プログラムの中で生成されるのではなく）外部から直接指定する（現状ではプロパティへの代入）感じでしょうか？

**Comment by ahahsak** [comment]
VB_HMMを生データで外部から利用するときは，プログラム内のinitialize_vbhmmで定義されているように，obsとn_stateから計算します．人工データの場合のみ外部から指定します．

**Comment by bromne** [comment]
1. 生データの場合  
    1. VB_HMM オブジェクトを生成する
    2. initialize_vbhmm を呼ぶ（ここで生データを投入？）
    3. show_model を呼ぶ
2. 人口データの場合
    1. VB_HMM オブジェクトを生成する
    2. プロパティ mu と cv に値を直接代入する
    3. show_model を呼ぶ

という流れでしょうか。（生データとは `obs` のことでいいでしょうか？）

**Comment by ahahsak** [comment]
生データ/人工データが obs のことで間違いないです．
流れは以下のようになります．
1.  生データの場合
 　  i.  VB_HMM オブジェクトを生成する．
　  ii.  fit を呼ぶ．（ここでデータを投入します）
　 iii.  show_model を呼ぶ．
2.  人工データの場合
 　  i.  VB_HMM オブジェクトを生成する．
　  ii.  プロパティ mu と cv に値を直接代入する．
　 iii.  simulate を呼ぶ．
　 iv.  fit を呼ぶ．（simulate で作った obs を投入）
  　v.  show_model を呼ぶ．

**Comment by bromne** [comment]
なるほど。ということは、 simulate に直接 `mu` や `cv` も渡せばよい気がします。（それでもまだ微妙ですが。）
